### ISSUE TITLE
Should this be moved to cosmology-tech?

### ISSUE THREAD

**Issue by gjermundgaraba** [cosmology-tech/telescope#314]
Preface: I don't know the history of telescope, or who "really" owns it. 

Context: every time I look for telescope I go to cosmology-tech, find what looks like an outdated fork of telescope, get promptly confused before remembering that for some reason this repo is under the Osmosis organization. Seems strange to me, and might be easier for user if the repo was located under what I can only assume is the org actually maintaining it.

I see that Osmosis has funded the creation of telescope, but it seems to be developed under the cosmology umbrella now? It seems to me that this would more logically be placed in the cosmology-tech repo to avoid confusion and keep things tidy and nice :)

Again, I don't know the history or the context enough, but just wanted to point out that this is a point of confusion. Feel free to close this if I am way off base or insulting anyone :sweat_smile:

**Comment by pyramation** [comment]
It's been moved! Thanks for the input. We were also having trouble with product management, so we've moved it to our github organization
