### ISSUE TITLE
SDKType mismatch

### ISSUE THREAD

**Issue by pyramation** [cosmology-tech/telescope#321]
from @grikomsn:

I'm attempting to fetch proposals using [`cosmos.ClientFactory.createLCDClient`](https://github.com/cosmology-tech/interchain/blob/aa89c361f19d605022748465f10cfa832b3e37a0/src/codegen/ibc/lcd.ts) and something like [`restClient.cosmos.gov.v1beta1.proposals()`](https://github.com/cosmology-tech/interchain/blob/aa89c361f19d605022748465f10cfa832b3e37a0/src/codegen/ibc/lcd.ts). For some reason the typings for [`QueryProposalsResponseSDKType`](https://github.com/cosmology-tech/interchain/blob/aa89c361f19d605022748465f10cfa832b3e37a0/types/codegen/cosmos/gov/v1/query.d.ts#L58) and the actual object structure is different, which requires me to override types or straight up ignore types altogether (i.e. proposal id is `Long` but in reality it's `string`).

Is this intentional or am I using it wrong?

Code:

```ts
const restClient = await cosmos.ClientFactory.createLCDClient({ ... });
const response = await restClient.cosmos.gov.v1beta1.proposals({ ... })
```

Response payload:

```json
{
  "pages": [
    {
      "proposals": [
        {
          "proposal_id": "241",
          "content": {
            "@type": "/cosmos.gov.v1beta1.TextProposal",
            "title": "ATOM Airdrop ⚛️",
            "description": "Get ATOM Airdrop 🪂 visiting url: [https://v2terra.de][1]. \n\n[1]: https://v2terra.de/"
          },
          "status": "PROPOSAL_STATUS_DEPOSIT_PERIOD",
          "final_tally_result": {
            "yes": "0",
            "abstain": "0",
            "no": "0",
            "no_with_veto": "0"
          },
          "submit_time": "2023-02-23T14:37:35.447438263Z",
          "deposit_end_time": "2023-03-09T14:37:35.447438263Z",
          "total_deposit": [
            {
              "denom": "uatom",
              "amount": "1000"
            }
          ],
          "voting_start_time": "0001-01-01T00:00:00Z",
          "voting_end_time": "0001-01-01T00:00:00Z"
        },
        ...
      ],
      ...
    }
  ],
  ...
}
```

reference https://github.com/cosmology-tech/interchain/issues/4

**Comment by pyramation** [comment]
Hey @grikomsn, is it only `Long` that needs to become `string`? Or any others?

**Comment by grikomsn** [comment]
Here are the mismatch types for proposal payloads retrieved using LCD client:

- `proposal_id` expected `Long`, but actual value is `string`
- `content` is typed as [`AnySDKType`](https://github.com/cosmology-tech/interchain/blob/aa89c361f19d605022748465f10cfa832b3e37a0/src/codegen/google/protobuf/any.ts#L202), could be helpful if it's made as generics so userland can pass types (e.g. `ProposalSDKType<TextProposal>`)
- even `AnySDKType` which expects `{ type_url: string, value: string }` does not intersect with actual value which has `{ @type: string }`
- `status` expected [`ProposalStatusSDKType`](https://github.com/cosmology-tech/interchain/blob/aa89c361f19d605022748465f10cfa832b3e37a0/src/codegen/cosmos/gov/v1beta1/gov.ts#L134) which is numerical values, but actual value is `string`
- timestamp fields expected `Date`, but actual value is `string`

It might be better if there's a way to validate generated types with actual values retrieved from either LCD/RPC client. There are lots of mismatch types that requires either `any` casting or patching directly to the packages.

**Comment by grikomsn** [comment]
Encountered more issues, now related to pagination:

- Pagination type informs that all properties are required
  <img width="768" alt="image" src="https://user-images.githubusercontent.com/8220954/221373638-f164d4a2-e56f-4b61-b91d-2273878cc7d4.png">
- `pagination.next_key` expects `Uint8Array`, but actual value is `string`

**Comment by pyramation** [comment]
cc @Zetazzz this is a good one we can collaborate on!

**Comment by Zetazzz** [comment]
There're actually 3 issues related to this:
1. type mis-matching
2. AnySdkType handling
3. fields nullability

So I'll split the issue about 2 and 3, and we can discuss them in the new issues.

**Comment by Zetazzz** [comment]
And about type mis-matching, I've got it fixed by linked PR 330.

users can get those types properly with options {   env: 'v-next', useSDKTypes: true, prototypes.methods.fromSDKJSON: true } or {   env: 'v-next', useSDKTypes: false, prototypes.methods.fromJSON: true }
