### ISSUE TITLE
add helpers to make BigInt compatible with JSON.stringify 

### ISSUE THREAD

**Issue by hoangdv2429** [cosmology-tech/telescope#402]
Currently we can have the option to encode/decode int64 as bigInt instead of Long. However, we're having a problem with display the response because `JSON.stringify` by default doesn't have the option to parse bigInt, as described in this [issue](https://github.com/GoogleChromeLabs/jsbi/issues/30). We should add helper to bigInt so that stringify can work with bigInt.

**Comment by Zetazzz** [comment]
const test= Proposal.fromPartial({
    id: BigInt(1),
    status: -1
  })
  // using toJSON can get string values of bigint inside
  const testJson = Proposal.toJSON(test);
  console.log(JSON.stringify(testJson));
  // and then using fromJSON to get original Proposal type with bigint inside
  const origTest = Proposal.fromJSON(testJson);
  console.log(origTest) 

I have to say it takes one more step... but this's currently the best we can do...

**Comment by Zetazzz** [comment]
I believe generating like this can solve the problem, and then we can make all functions that returns the interface(Proposal) using this creation:

function createBaseProposal(): Proposal {
  return {
    id: BigInt(0),
    messages: [],
    status: 0,
    finalTallyResult: TallyResult.fromPartial({}),
    submitTime: undefined,
    depositEndTime: undefined,
    totalDeposit: [],
    votingStartTime: undefined,
    votingEndTime: undefined,
    metadata: "",
    toJSON: function(){
      return Proposal.toJSON(this)
    }
  } as Proposal;
}

I've tested and it's working:

  const test= Proposal.fromPartial({
    id: BigInt(1),
    status: -1
  })

  // it will call toJSON inside and work
  let testString = JSON.stringify(test);

  console.log(testString);

  let testJson = JSON.parse(testString)
  // get back with the string id.
  console.log(testJson)

  // and then using fromJSON to get original Proposal type with bigint inside
  const origTest = Proposal.fromJSON(testJson);
  console.log(origTest)

Hope this make sense. If you like the solution, I can make the change.

**Comment by hoangdv2429** [comment]
Lgtm! We can add toJSON to createBase function that have bigInt fields and it should be good!

**Comment by hoangdv2429** [comment]
@Zetazzz can you review the PR above

**Comment by hoangdv2429** [comment]
let ppl define they own way of parsing object with bigInt
