### ISSUE TITLE
Unable to generate fromJSON and toJSON

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [cosmology-tech/telescope#414]
when generating proto libraries, I face this problem

<img width="1512" alt="Screenshot 2023-07-10 at 13 42 03" src="https://github.com/osmosis-labs/telescope/assets/23058164/883cb19b-4949-4522-b04c-0eeed6fa93e7">

Basically, no fromJSON and toJSON which is incompatible with GeneratedType from @cosmjs/proto-signing.

I am using telescope 0.99.10

**Comment by Zetazzz** [comment]
Hi, we've launched telescope v1.0 and we've been using a config file instead of setting those properties.

So you can try the new version out.

Thank you very much!

**Comment by Zetazzz** [comment]
I believe when you're using config file and config properly, this wouldn't happen. So I'll close this for now, if there's any further issue, we can reopen this.

Thanks for your feedback!
