### ISSUE TITLE
Using an embedded message in another file results in invalid typescript generation

### ISSUE THREAD

**Issue by clemire** [cosmology-tech/telescope#418]
Hi folks, we have a message defined within a message like this:

```
message TestMessage {
  message SubMessage {
    int32 id = 1;
  }
}
```

If I use that message in another proto within the same file, the code I transpile with telescope has no issues.

However, if I use that message in another file, say the genesis file, the resulting generated code results in an error. Example:

// in genesis.proto of same package
```
message GenesisState {
  TestMessage.SubMessage example = 1;
}
```

Then when I run `tsc` on the transpiled code, I get the following error message (I'm leaving in the file paths):

```
src/codegen/dydxprotocol/assets/genesis.ts:14:13 - error TS2304: Cannot find name 'TestMessage_SubMessageSDKType'.

14   example?: TestMessage_SubMessageSDKType;
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/codegen/dydxprotocol/assets/genesis.ts:14:13 - error TS4033: Property 'example' of exported interface has or is using private name 'TestMessage_SubMessageSDKType'.

14   example?: TestMessage_SubMessageSDKType;
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors in the same file, starting at: src/codegen/dydxprotocol/assets/genesis.ts:14
```

So it looks like this submessage type is not being properly imported into the codegenned file.

(Is this enough information to be unambiguous? LMK!)

**Comment by pyramation** [comment]
can you provide some source code or a reproduceable example?

**Comment by pyramation** [comment]
this should be fixed now!

**Comment by BrendanChou** [comment]
> this should be fixed now!

Thanks! We will see if we can test it out
