### ISSUE TITLE
Unsupported type: '/ethermint.types.v1.EthAccount'

### ISSUE THREAD

**Issue by chismo950** [cosmology-tech/telescope#428]
It is said cosmjs do not support type: '/ethermint.types.v1.EthAccount': https://github.com/cosmos/cosmjs/issues/1351
I use telescope to generate our js client and encounter this issue, our project uses EthAccount type.
Can telescope add the ethermint support?

**Comment by praveen836845** [comment]
const { DirectSecp256k1HdWallet , DirectSecp256k1Wallet } = require("@cosmjs/proto-signing");
const { SigningStargateClient, coins } = require("@cosmjs/stargate");
const  { fromHex, toHex , toBech32 } = require("@cosmjs/encoding"); // for converting hex to byte array
const { stringToPath } = require('@cosmjs/crypto');
const {bech32Converter } = require('bech32-converting');

const { ethers } = require("ethers");

const RPC_ENDPOINT = "https://tendermint-rpc.testnet.ms/"; // Replace with the actual RPC endpoint
const DENOM = "XFI"; // Token denomination (native token)
const CHAIN_ID = "crossfi-chain"; // Replace with the actual chain ID

// Replace with your wallet's mnemonic phrase
const MNEMONIC = "whale help defy mention school bread produce wife chalk spirit someone address";
const HD_PATHS =  [stringToPath("m/44'/60'/0'/0/0")];


// Replace with the recipient's address
const RECIPIENT_ADDRESS = "mx1hn9vuykzw8n0f2xp3mlnr9m6unf4jydaa3nqxh"; // Replace with the recipient's address
const AMOUNT = "1"; // 1 MPX (adjust as needed)

async function sendMpx() {
  try {
    // Initialize wallet using the mnemonic
    const wallet = await DirectSecp256k1HdWallet.fromMnemonic(MNEMONIC, {hdPaths: HD_PATHS , prefix: "mx"  });

     
    // Retrieve the sender's account address
    const [oldAddressAccountData ,newAddressAccountData] = await wallet.getAccounts();
    console.log("newAddress" , newAddressAccountData);
    const senderAddress  = convertToCosmosAddress("0x50FdF14765b161f1a4f2953e7F57cc6F24F54Ba9")  // evm based address


    // const senderAddress = bech32Converter('mx').toHex(oldAddressAccountData.address)
    console.log("Sender Address:", senderAddress);
    // Connect to the CrossFi chain
    const client = await SigningStargateClient.connectWithSigner(RPC_ENDPOINT, wallet);
     console.log("signer is created or not" , client);
    // Prepare the transaction fee
    const fee = {
      amount: coins(5000, DENOM), // Adjust fee amount as required
      gas: "200000", // Adjust gas limit as required
    };

    // Execute the token transfer
    console.log(`Sending ${AMOUNT} ${DENOM} from ${senderAddress} to ${RECIPIENT_ADDRESS}...`);
    const result = await client.sendTokens('0xbccACE12C271E6F4A8c18Eff31977Ae4D35911bd', '0x2f7CF10AbA819e03e7442e8428a9F75B2f56DA14',   [{ denom: "xfi", amount: "500000000000000000" }], {
                 amount: [{ denom: "xfi", amount: "500" }],
              gas: "200000",
            });

    // Log the transaction result
    console.log("Transaction Result:", result);

    if (result.code === 0) {
      console.log("Transaction successful!");
    } else {
      console.error("Transaction failed:", result.rawLog);
    }
  } catch (error) {
    console.error("Error during transaction:", error.message);
  }
}

// Call the function
sendMpx();

async function listAccounts() {
    try {

        // const mnemonic = await DirectSecp256k1HdWallet.generate(24)
        // const account =  await mnemonic.getAccounts();
        // console.log(await mnemonic.getAccounts());
        // const address = account[0].address
        // console.log('address' , address);
        const walletfromEthermint = ethers.Wallet.fromPhrase(MNEMONIC);
        const privatekeyHexformat = fromHex(walletfromEthermint.privateKey.slice(2))
        const cosWallet = await DirectSecp256k1Wallet.fromKey(privatekeyHexformat, 'mx');

        console.log("cosmosWallet" , cosWallet)
        const cosmosAddress = await cosWallet.getAccounts();

        console.log(">> checking that address is same testXFI console" , cosmosAddress[0].address)
        console.log("*****************************************************************************")
        const privatekeyget = ethers.Wallet.fromPhrase(MNEMONIC).privateKey;
 const buffprivatekey = fromHex(privatekeyget.slice(2))
    const wallet = await DirectSecp256k1Wallet.fromKey(buffprivatekey, "mx");
    //   console.log("wallet generated through privateKey" , wallet)
      const accounts = await wallet.getAccounts();
      accounts.forEach((account, index) => {
        console.log(`Account ${index}: Address = ${account.address}`);
      });
    console.log("***************************************************************************************")
      const wallet1 = await DirectSecp256k1HdWallet.fromMnemonic(MNEMONIC, { prefix: "mx" });
      const accounts1 = await wallet1.getAccounts();
      accounts1.forEach((account, index) => {
        console.log(`Account ${index}: Address = ${account.address}`);
      });
  




    } catch (error) {
      console.error("Error listing accounts:", error.message);
    }
  }
  
//   listAccounts();


function convertToCosmosAddress(evmPublicKey) {
    // Convert the public key to a Uint8Array
    const pubkeyUint8Array = fromHex(evmPublicKey.slice(2)); // Remove 0x and convert to byte array
  
    // Encode the public key in Bech32 format with the CrossFi 'mx' prefix
    const cosmosAddress = toBech32('mx', pubkeyUint8Array);
    console.log("Cosmos Address 2: ", cosmosAddress);
    return cosmosAddress;
  }

i'm facing the same problem can anyone please tell me what's the solution of this one . getting Unsupported Ethermint account type
