### ISSUE TITLE
move methods that are creating circular deps between proto-parser/ast into utils/types pkgs

### ISSUE THREAD

**Issue by pyramation** [cosmology-tech/telescope#430]
imports like this are apparently in the `ast` package, sometimes creates a circular dep:

```
import { getNestedProto, ProtoStore } from "@cosmology/proto-parser";
```

I think `ProtoStore` maybe we make an `interface` — and in `proto-parser` we implement the interface, but the interface can live in `@cosmology/types`.

the `getNestedProto` and other proto lookup methods can be in `@cosmology/utils`

**Comment by Zetazzz** [comment]
Done in published @cosmology/telescope@0.104.0
