### ISSUE TITLE
Mismatched interface and class types

### ISSUE THREAD

**Issue by NoahSaso** [cosmology-tech/telescope#437]
When generating `/cosmos.base.tendermint.v1beta1.query.GetBlockByHeightResponse`, it seems the interface and function are getting generated with mismatching types, resulting in a build error.

This interface is generated:
```ts
/** GetBlockByHeightResponse is the response type for the Query/GetBlockByHeight RPC method. */
export interface GetBlockByHeightResponse {
  blockId: BlockID | undefined;
  /** Deprecated: please use `sdk_block` instead */
  block: Block1 | undefined;
  /** Since: cosmos-sdk 0.47 */
  sdkBlock: Block2 | undefined;
}
```

With this creator function:
```
function createBaseGetBlockByHeightResponse(): GetBlockByHeightResponse {
  return {
    blockId: BlockID.fromPartial({}),
    block: Block.fromPartial({}),
    sdkBlock: Block.fromPartial({})
  };
}
```

Neither `Block` is not found because they are imported as `Block1` and `Block2`:
```ts
import { Block as Block1 } from "../../../../tendermint/types/block";
import { Block as Block2 } from "./types";
```

**Comment by NoahSaso** [comment]
This is happening for `/cosmos.tx.signing.v1beta1.signing.SignatureDescriptor` as well:
```ts
/**
 * SignatureDescriptor is a convenience type which represents the full data for
 * a signature including the public key of the signer, signing modes and the
 * signature itself. It is primarily used for coordinating signatures between
 * clients.
 */
export interface SignatureDescriptor {
  /** public_key is the public key of the signer */
  publicKey: Any | undefined;
  data: SignatureDescriptor_Data | undefined;
  /**
   * sequence is the sequence of the account, which describes the
   * number of committed transactions signed by a given address. It is used to prevent
   * replay attacks.
   */
  sequence: Long;
}
```

whose creator function ends up being:
```
function createBaseSignatureDescriptor(): SignatureDescriptor {
  return {
    publicKey: Any.fromPartial({}),
    data: Data.fromPartial({}),
    sequence: Long.UZERO
  };
}
```

`Data` should be `SignatureDescriptor_Data`.

There seems to be some issue with types getting renamed for a specific context but the contextual name is only getting used in the interface whereas the source name is getting used in the base creator function.

**Comment by pyramation** [comment]
@Zetazzz here are the relevant lines:

### `GetBlockByHeightResponse `

-  https://github.com/cosmology-tech/interchain/blob/ec493eb4402e29d05f259c57be9cde311d4eebac/packages/interchain-query/src/codegen/cosmos/base/tendermint/v1beta1/query.ts#L1220-L1221
- https://github.com/cosmology-tech/interchain/blob/ec493eb4402e29d05f259c57be9cde311d4eebac/packages/interchain-query/src/codegen/cosmos/base/tendermint/v1beta1/query.ts#L4-L7

We have a helper function for dealing w the `Block1` and `Block2` business, should be a simple fix

### `SignatureDescriptor`

- https://github.com/cosmology-tech/interchain/blob/ec493eb4402e29d05f259c57be9cde311d4eebac/packages/interchain/src/codegen/cosmos/tx/signing/v1beta1/signing.ts#L339
- https://github.com/cosmology-tech/interchain/blob/ec493eb4402e29d05f259c57be9cde311d4eebac/packages/interchain/src/codegen/cosmos/tx/signing/v1beta1/signing.ts#L141

We also have a helper function for dealing w the nested types, this is also probably a simple fix

**Comment by Zetazzz** [comment]
Done
