### ISSUE TITLE
Add all types to registry and amino converters

### ISSUE THREAD

**Issue by NoahSaso** [cosmology-tech/telescope#442]
I noticed that only the TX message types are getting added to the registry and amino converter object. However, there are many non-msg types that need encoding, such as `/cosmos.auth.v1beta1.ModuleAccount`. I create a registry and then use the registry's `lookupType`, `encode`, and `decode` functions to manually do encoding where necessary, and it would be very useful if I could automatically create a registry with all known protobuf types, not just for transaction signature purposes.

**Comment by pyramation** [comment]
I wonder if we need to add all messages or if there is a way we can use our dep resolver to only load required ones.

**Comment by pyramation** [comment]
![telegram-cloud-photo-size-1-5098102296495107188-y](https://github.com/cosmology-tech/telescope/assets/545047/eb7bb650-49a6-4202-80a1-b612c805a505)

![telegram-cloud-photo-size-1-5098102296495107187-y](https://github.com/cosmology-tech/telescope/assets/545047/6ce23679-17ad-48d6-8aed-6d264e28cc6f)

![telegram-cloud-photo-size-1-5098102296495107186-y](https://github.com/cosmology-tech/telescope/assets/545047/08166f24-9149-4401-93e5-cd07403cedc0)

**Comment by NoahSaso** [comment]
> I wonder if we need to add all messages or if there is a way we can use our dep resolver to only load required ones.

Aren't all types either used in a msg, query request, or response somewhere? Wouldn't the required dependency tree just end up including all of them?

**Comment by pyramation** [comment]
I have a suspicion this is solved with closing of this https://github.com/cosmology-tech/telescope/issues/118 but the interfaces aren't registered

**Comment by NoahSaso** [comment]
> I have a suspicion this is solved with closing of this #118 but the interfaces aren't registered

oh interesting

**Comment by pyramation** [comment]
this may be closeable

**Comment by Zetazzz** [comment]
This will be handled better after this issue's done:
https://github.com/cosmology-tech/telescope/issues/401
So I'll close this one for now, Thank you very much.
