### ISSUE TITLE
Question: Is it possible to remove ___InterfaceDecoder from generated files ?

### ISSUE THREAD

**Issue by bz888** [cosmology-tech/telescope#454]
Hey, new to telescope, just wondering if there are any possible ways to have the generated files not to include?

e.g.
```
export const Authorization_InterfaceDecoder = (input: _m0.Reader | Uint8Array): GenericAuthorization | SendAuthorization | StakeAuthorization | Any => {
  const reader = input instanceof _m0.Reader ? input : new _m0.Reader(input);
  const data = Any.decode(reader, reader.uint32());
  switch (data.typeUrl) {
    case "/cosmos.authz.v1beta1.GenericAuthorization":
      return GenericAuthorization.decode(data.value);
    case "/cosmos.bank.v1beta1.SendAuthorization":
      return SendAuthorization.decode(data.value);
    case "/cosmos.staking.v1beta1.StakeAuthorization":
      return StakeAuthorization.decode(data.value);
    default:
      return data;
  }
};
```
With this generated function i am getting getting compilation errors, just wondering if there are any ways for me not include this in the generated files (im actually not sure what this does)? I am only really after the generated interfaces.
err: ` TS2693: 'Any' only refers to a type, but is being used as a value here.`

I have seen this issue, however, ideally for my usage, adding more files to the ignore list would not be ideal. 
https://github.com/cosmology-tech/telescope/pull/408#issuecomment-1639657255 

Thank you in advance

**Comment by Zetazzz** [comment]
HI, yes, try this then you can disable:
  interfaces: {
    enabled: false,
    useUnionTypes: false
  },

We're fixing these, Thank you very much!

**Comment by bz888** [comment]
@Zetazzz it works! thank you so much
