### ISSUE TITLE
need to make sure tendermint37 client is also working

### ISSUE THREAD

**Issue by Zetazzz** [cosmology-tech/telescope#469]
we also need to make sure tendermint37 client is also working, while currently telescope's working with 34

**Comment by hoangdv2429** [comment]
@Zetazzz Can I work on this ? also can you give me more context (like a list of criteria) for this issue ?

**Comment by Zetazzz** [comment]
Hi, yes, that'll be great.

In fact, I don't know much about the difference of 34 and 37.
What I can tell is that, there're some Tendermint34Client.connect inside generated code. And Tendermint34Client is from @cosmjs/tendermint-rpc. So I guess if we'll support Tendermint37Client(also in @cosmjs/tendermint-rpc) as well, we just have to add a flag and replace those clients and test if the code's still working with 37client.

Thank you very much!
