### ISSUE TITLE
add comments from protos

### ISSUE THREAD

**Issue by liujun93** [cosmology-tech/telescope#502]
take `gov.v1beta1` as example

comments in proto: 
```
// Query defines the gRPC querier service for gov module
service Query {
  // Proposal queries proposal details based on ProposalID.
  rpc Proposal(QueryProposalRequest) returns (QueryProposalResponse) {
    option (google.api.http).get = "/cosmos/gov/v1beta1/proposals/{proposal_id}";
  }
```

NO comments in codegen
```
export class QueryClientImpl implements Query {
  proposal(request: QueryProposalRequest): Promise<QueryProposalResponse> {
    const data = QueryProposalRequest.encode(request).finish();
    const promise = this.rpc.request("cosmos.gov.v1beta1.Query", "Proposal", data);
    return promise.then(data => QueryProposalResponse.decode(new BinaryReader(data)));
  }
```

**Comment by hoangdv2429** [comment]
The comments you mentioned will be in the interface. When you use the function in vscode, It will show up as suggestion.
<img width="554" alt="Screenshot 2023-10-31 at 20 40 37" src="https://github.com/cosmology-tech/telescope/assets/63839106/953e1ee1-e336-41dd-86e7-f12acead4742">

**Comment by pyramation** [comment]
comments technically will add more bloat if we duplicate them. I think if they're in the interface should be sufficient
