### ISSUE TITLE
Amino encoder incorrectly including `omitempty` boolean when false

### ISSUE THREAD

**Issue by NoahSaso** [cosmology-tech/telescope#522]
The `/cosmwasm.wasm.v1.MsgInstantiateContract2` type has a `FixMsg` boolean that has `omitempty` in its go struct definition. Somewhat unintuitively, this means that whenever it is `false`, it should be ommitted, and whenever it is `true`, it should be set.

This is correctly represented by the protobuf encoder here:
<img width="346" alt="Screenshot 2023-11-14 at 09 18 31" src="https://github.com/cosmology-tech/telescope/assets/6721426/e94c7186-e031-4d13-a3fb-1626c2242c1b">

but is incorrectly represented in the Amino encoder:
<img width="251" alt="Screenshot 2023-11-14 at 09 18 57" src="https://github.com/cosmology-tech/telescope/assets/6721426/c57aa45e-0d24-4a2e-b5b1-6e8e37283316">

To fix this, I believe these changes should be made to `toAmino` and `fromAmino` respectively:
<img width="269" alt="Screenshot 2023-11-14 at 09 19 22" src="https://github.com/cosmology-tech/telescope/assets/6721426/b9e75e8e-6875-4282-a8d9-4db0652afc78">
<img width="275" alt="Screenshot 2023-11-14 at 09 19 27" src="https://github.com/cosmology-tech/telescope/assets/6721426/12cd294d-88b2-4891-a68d-14e5afb57b76">

**Comment by Zetazzz** [comment]
Fixed by this PR:
https://github.com/cosmology-tech/telescope/pull/537
