### ISSUE TITLE
concentrated liquidity does not exist on typeof osmosis

### ISSUE THREAD

**Issue by RonCan** [cosmology-tech/telescope#554]
I have just setup with most basic settings and find that the concentratedliquidity module is not there. Am I supposed to enable some settings in `.telescope.json` for it to work? I noticed that by default when you install osmosis from registry the proto folder doesn't come with concentratedliquidity module.

**Comment by pyramation** [comment]
this is better for the osmojs repository

https://github.com/osmosis-labs/osmojs/tree/09bd69011ad3aedf045a5816e70f34c8276885ae/packages/osmojs/src/codegen/osmosis/concentrated-liquidity
