### ISSUE TITLE
toAmino errors

### ISSUE THREAD

**Issue by liujun93** [cosmology-tech/telescope#573]
1. `omitDefault` is missing for `string` type when value is `""`. i.e. `/ibc.applications.transfer.v1.MsgTransfer` property `memo`
2. `voteOptionToJSON` should return number rather than string. i.e. should be `"option":1` rather than `"option":"VOTE_OPTION_YES"`

**Comment by Zetazzz** [comment]
2's fixed and 1's being dealt with in a PR
