### ISSUE TITLE
return usable types from toJSON

### ISSUE THREAD

**Issue by turadg** [cosmology-tech/telescope#605]
The `toJSON` method on the generated classes returns a transformation of the data that can be JSON-encoded. E.g. `UInt8Array` becomes a Base64 string.

Currently those methods return `unknown` but they could return an actual type by wrapping existing interfaces in a utility types.

Consider,
```ts
export interface Duration {
  seconds: bigint;
}
```

The [`Duration` class's `toJSON`](https://github.com/Agoric/agoric-sdk/blob/3f2b479d60917c90a1e9fc3013247812747fa3c0/packages/cosmic-proto/src/codegen/google/protobuf/duration.ts#L190-L205) could return that instead of `unknown` as it does now:

```ts
export const Duration = {
  typeUrl: '/google.protobuf.Duration',

  toJSON(message: Duration): JsonSafe<Duration> {
    const obj: any = {};
    message.seconds !== undefined &&
      (obj.seconds = (message.seconds || BigInt(0)).toString());
    message.nanos !== undefined && (obj.nanos = Math.round(message.nanos));
    return obj;
  },
}
```

A case with `UInt8Array`:
```ts
export interface RequestQuery {
  data: Uint8Array;
  path: string;
  height: bigint;
  prove: boolean;
}
```

An example of a utility that would handle both:
```ts
type JsonSafe<T> = {
  [Prop in keyof T]: T[Prop] extends Uint8Array ? string : T[Prop] extends bigint ? string : T[Prop];
}
```
([playground link](https://www.typescriptlang.org/play?target=99&jsx=0#code/C4TwDgpgBAUgzgewHYGUCGAzCAeAKgPigF4oBvAWACgooBtABQCcEwoBLJKAawhAQyi4AugC5BDZmCFQIAD2AQkAEzhQAqh2AAOAIKNGaEFAD8UOMEYcA5lDG4JLaXIXLVAIzZXNJsxeu3xJkcAbioAXyoqAHooqAARAFcDYDZkaNiAC2BgMDgRGK9gDIS3ADoAYwQAWyidKwRLcqi0esaAWjglLii3ABsENyiAZgwAJjcAFgB2AE4lADYABhmARinymcW0FYgZjHKhxZWh0emtFdGp6Yw0IfLFqLA0cq4WiDgoyrgqtnK2sGYwAQUTgjCalSUECsiii9QQVl6EEegIGCQwUSUSTQKWQpWAcAAxAAZFabNpE0aLACskUocjADWA7CQCkYN3K0ESyVSnAo1CgUQAVIKqDQoIKoChPEgIEozBBKq4oPwoEVoHAnpwVSkqhBSlAALIJcxQNzQDDMKpQNpDFZUgA0VKm83tizdrrdopoEqBUAA1LaHU6XW7Fh7Fszyr1jWwAG56qAAOQQCjEarg0DcCASSrQjGglSqYASCjlFuqIi94qgS3lTR+nAltYbUQyjGrpygbYxhmrQ3mVNKoypUCUhg+IAgeerK1DEcnebgVcFUS9GcVKjEHi8LNC-KFIv51alVhlZYM5RxSFUKrQdeQcuxUCQaCQCHXD6g+cQ0avyoEapmJqy7-qqbC6vqXLYjyqiInAqhFK+yoyveyhQHm0D5gC7yKKWUAAO5sEU6FQIsIEAAYfq45FQBgbAQL0j5oXeDJwERcbQA0z5QtB8ZQORL5vnANF0QxSj6gAYlxmLcsgS5HhKKrIOqCqflxVQNBA9okW+SBtAAXhAzBQLGaDRuaXGAQJr7viJ9GMVAVTGkyZogdqGTqmgupmNK6EIR5-FUSodlifqRommatGWtaMyxfasUzPFsUgb6foJUliUJZG0ZsfGpTLqu-KCe+YhIAkVRmowe4RJQVD0oyUCKiaUF-iQfI0KAkBqIwvRiAA5LCCDwoipQAimqIYKULU8n19q0h1CAwCgADyiYABS6vBbxiNNyAAJRiPAyDoFg2C7UghDtWKTVMgMABWYivkYbVhHuYqOe8cBvKUQWqAAhEQJA5pCdFnlAABk4NVmKa33T9qlKiQG2fd9v1QAAPujUAAEKeAAkiya2LHte14ggKB+EgVhrSTb1iptX3QqUxX-YDUDAxAoOyhD4NQLDbh3czNmqCQBrYhkpTMMDyNbUzLO09D+bAEkWoC3TYRzZQNXpFAABKEAAI4JO8wAAIrG4wIB1bIDKMEymhGey0D60bJvm0ZRhXWOwBoGIGgsro+iGHTTxFGI5iWFTdMeZ4WRbp4mgh8w8ZbkNiKvtVtI3V+BvEGQYR+bAiCoJgOAu8b5ju5b+B7owBulN7aA-T7dtwAA6kRGS1-XMdWFkzd5viHdFHuVBAA))

**Comment by pyramation** [comment]
should be good to go!

https://github.com/cosmology-tech/telescope/pull/620

should be able to publish after confirmation
