### ISSUE TITLE
Default deprecated fields to be nullable

### ISSUE THREAD

**Issue by Zetazzz** [cosmology-tech/telescope#666]
default deprecated fields, such as with (gogoproto.moretags) = "yaml:\"denom0\",deprecated:\"true\"" , to be nullable

**Comment by Zetazzz** [comment]
deprecated:"true" => the filed is optional
none or deprecated:"false" => the filed is not optional

**Comment by NorOldBurden** [comment]
solved by https://github.com/cosmology-tech/telescope/pull/670
